GET http://localhost:8800/api/auth/registerajskajs

###
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "email" : "admin1@gmail.com",
    "password": "1234567"
}

###
POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "email" : "admin2@gmail.com",
    "password": "1234567"
}

### authorazation with jwt
GET http://localhost:8800/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzE4MDE0MTYyLCJleHAiOjE3MTg0NDYxNjJ9.HJbB7sZPVcQEzd2n0G1LjQGG3qUQ-iCHmJjchPehrec

### get job
GET http://localhost:8800/api/job/

### get job by name
GET http://localhost:8800/api/job/?job_type_code=ON
    
### get job by name
GET http://localhost:8800/api/job/?name=Ky su

### get job by order and 
GET http://localhost:8800/api/job/?order[]=id&order[]=DESC&limit=2&page=2

### get job by order date create 
GET http://localhost:8800/api/job/?order[]=createdAt&order[]=DESC

### Search 
GET http://localhost:8800/api/job/?name=marketing&province_cong_viec=DN&salary_code=1-3

### pagination 
GET http://localhost:8800/api/job/?page=2


### get degree
GET http://localhost:8800/api/degree/